@env=dev

### 회원가입
POST http://localhost:{{SERVER_PORT}}/api/v1/auth/signup
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "test1234!",
  "name": "test",
  "phone": "01012341234",
  "profileImageUrl": "test.jpg"
}


### 로그인
POST http://localhost:{{SERVER_PORT}}/api/v1/auth/sign-in
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "test1234!"
}

> {%
    client.global.set("at", response.body.data.accessToken);
 %}


### 로그아웃
POST http://localhost:{{SERVER_PORT}}/api/v1/auth/sign-out
Content-Type: application/json
Authorization: Bearer {{at}}
